### PR TITLE
Issue #9083 PodcastBundle: fixed public images

### PR DESCRIPTION
**Pull request by mreyk**

### CODE REVIEW

**Comment by rubenrua** [comment]
Into 2.2.x too.

**Comment by mreyk** [comment]
Deleted too soon the branch. Cherry-pick commit into 2.2.x?

**Comment by rubenrua** [comment]
I undeleted it.

**Comment by mreyk** [comment]
Done cherry pick e614bb6eedc24702b499350047a9b8b147e37f20

**Pull request merged**
